### PR TITLE
Improve comments file.

### PR DESCRIPTION
**Pull request by tfrommen**
Improve formatting.
**Note:** I changed two translation strings ( `'Name %s'`  &rarr; `'Name'`, and `'Email %s'` &rarr; `'Email'`).

Also, personally I would set the screen reader title _Comment navigation_ not inside an `h2`, but rather an `h4` (the actual _Comments_ title is an `h3`, BTW).

### CODE REVIEW

**Comment by Moonomo** [comment]
Why not `Name %s` and `Email %s`? Isn't it the right way to make sure RTL supports are fine,  if we add RTL support to the theme in the future?

I missed using `esc_html_x` on `$req_text` variable. 

I agree on using h3, or h4- both makes more sense.

Regarding the `,` at end of an array values- I had used it throughout the code-base, as if like a convention- a habit. Not seeing benefit of removing it- :)

**Comment by tfrommen** [comment]
> Why not `Name %s` and `Email %s`? Isn't it the right way to make sure RTL supports are fine, if we add RTL support to the theme in the future?

Ah, okay, I didn't think of RTL support here. Yes, if you (sometime) want to add this, this totally makes sense.

I changed the strings because you always have a space there (even if there is no required mark). This is no problem, just something I didn't like. :) So, you can go ahead and ignore/close this PR, or tell me how to adapt it for merge.

Regarding the trailing array commas: I didn't remove them, I added them...? :)

**Comment by Moonomo** [comment]
Sorry about the comma, then probably I removed it intentionally. LOL

**Review by Moonomo — CHANGES_REQUESTED** [review]
If we are to add `,` we should do it everywhere- most likely it would be best to not doing it. And for RTL the `sprintf` should be there. 

I like the type casting, also please go ahead and change the h2 for the comment navigation title to h3, or h4- no problem.

**Comment by tfrommen** [comment]
Updated.

**Review by Moonomo — APPROVED** [review]

**Pull request merged**
